### ISSUE TITLE
Can't access WHU MVS dataset

### ISSUE THREAD

**Issue by isaaccorley** [gpcv-liujin/REDNet#10]
The link to the dataset seems to be down. Is it possible to upload the dataset somewhere more stable e.g. Google Drive, OneDrive, etc.?

**Comment by gpcv-liujin** [comment]
> The link to the dataset seems to be down. Is it possible to upload the dataset somewhere more stable e.g. Google Drive, OneDrive, etc.?

Sorry for that, the server is under maintenance. I will upload the dataset to a more convenient platform as soon as possible. If you need this dataset urgently, please let me know.

**Comment by isaaccorley** [comment]
No rush. Thanks for letting me know.

**Comment by gpcv-liujin** [comment]
> No rush. Thanks for letting me know.

The dataset have been upload  to  baidu disk. 
The link in baidu disk: https://pan.baidu.com/s/1aGHFfW26Q8T4oCVa2tPZYQ  
                           code：91ae

**Comment by isaaccorley** [comment]
I see it in the readme now, thanks!
