### ISSUE TITLE
visualization

### ISSUE THREAD

**Issue by kwea123** [gpcv-liujin/REDNet#2]
What software do you use to visualize the point cloud in Fig. 7? It seems that the number of points is huge, how do you visualize all points without crashing?

**Comment by gpcv-liujin** [comment]
> What software do you use to visualize the point cloud in Fig. 7? It seems that the number of points is huge, how do you visualize all points without crashing?

**Comment by gpcv-liujin** [comment]
> What software do you use to visualize the point cloud in Fig. 7? It seems that the number of points is huge, how do you visualize all points without crashing?

The visualization software I used is Cloudcompare, which can load hundreds of millions of points simultaneously without crashing. The down-sampling function in the software can reduce the density of points to make the global display smoother.

**Comment by gpcv-liujin** [comment]
> What software do you use to visualize the point cloud in Fig. 7? It seems that the number of points is huge, how do you visualize all points without crashing?

The visualization software I used is Cloudcompare, which can load hundreds of millions of points simultaneously without crashing. The down-sampling function in the software can reduce the density of points to make the global display smoother.
