### ISSUE TITLE
Cannot find the pre-trained REDNet model

### ISSUE THREAD

**Issue by FengQiaojun** [gpcv-liujin/REDNet#3]
Do you mind checking the link to the pre-trained model? [http://gpcv.whu.edu.cn/data/download/MODEL_FOLDER.zip](http://gpcv.whu.edu.cn/data/download/MODEL_FOLDER.zip) can not be reached.

**Comment by gpcv-liujin** [comment]
> Do you mind checking the link to the pre-trained model? http://gpcv.whu.edu.cn/data/download/MODEL_FOLDER.zip can not be reached.
Sorry that we missed this link when updating the server. Now the model has been re-uploaded. You can get it from 'https://github.com/gpcv-liujin/REDNet/blob/master/MODEL_FOLDER/MODEL_FOLDER.zip'

**Comment by gpcv-liujin** [comment]
> Do you mind checking the link to the pre-trained model? http://gpcv.whu.edu.cn/data/download/MODEL_FOLDER.zip can not be reached.

Sorry that we missed this link when updating the server. Now the model has been re-uploaded. You can get it from 'https://github.com/gpcv-liujin/REDNet/blob/master/MODEL_FOLDER/MODEL_FOLDER.zip'

**Comment by FengQiaojun** [comment]
Thank you!
